name: Android CI (APK & optional AAB)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms & build-tools
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0" "platform-tools"

      - name: Set up Gradle (no wrapper needed)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Build Debug APK
        run: |
          gradle :app:assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/*.apk

      # -------- OPTIONAL (uncomment to build unsigned release AAB) --------
      # - name: Build Release AAB (unsigned)
      #   run: |
      #     gradle :app:bundleRelease
      # - name: Upload Release AAB (unsigned)
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-aab-unsigned
      #     path: app/build/outputs/bundle/release/*.aab

      # -------- OPTIONAL SIGNING (Play Store) --------
      # Requires you to add repository secrets: KEYSTORE_BASE64, KEYSTORE_PASSWORD, KEY_ALIAS, KEY_PASSWORD
      # and to have a release signingConfig in app/build.gradle.kts that reads these env vars.
      # - name: Decode keystore
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   run: |
      #     echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > my-release-key.jks
      #
      # - name: Build Signed Release AAB
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   env:
      #     STORE_FILE: my-release-key.jks
      #     STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #   run: |
      #     gradle :app:bundleRelease
      #
      # - name: Upload Signed Release AAB
      #   if: ${{ secrets.KEYSTORE_BASE64 != '' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release-aab-signed
      #     path: app/build/outputs/bundle/release/*.aab
